title: My new Jekyll site
email: your-email@domain.com
description: This is my awesome site powered by Jekyll!
baseurl: ''
url: brianfeister.github.io
twitter_username: jekyllrb
github_username: brianfeister
markdown: kramdown
theme: clean-jekyll
